### ISSUE TITLE
Deploy fails with javadoc generation errors

### ISSUE THREAD

**Issue by sergiofbsilva** [FenixEdu/fenixedu-maven#3]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:2.9.1:jar (attach-javadoc) on project fenixedu-spaces: MavenReportException: Error while creating archive:
[ERROR] Exit code: 1 - /home/marvin/git/fenixedu-spaces/src/main/java/org/fenixedu/spaces/domain/Information.java:301: warning: no description for @param
[ERROR] \* @param checkpoint
[ERROR] ^
[ERROR] /home/marvin/git/fenixedu-spaces/src/main/java/org/fenixedu/spaces/domain/Information.java:302: warning: no description for @return
[ERROR] \* @return
[ERROR] ^
[ERROR] /home/marvin/git/fenixedu-spaces/src/main/java/org/fenixedu/spaces/domain/Space.java:112: warning: no description for @return
[ERROR] \* @return
[ERROR] ^
[ERROR] /home/marvin/git/fenixedu-spaces/src/main/java/org/fenixedu/spaces/domain/Space.java:121: warning: no description for @param
[ERROR] \* @param when
[ERROR] ^
[ERROR] /home/marvin/git/fenixedu-spaces/src/main/java/org/fenixedu/spaces/domain/Space.java:122: warning: no description for @return
[ERROR] \* @return
[ERROR] ^
[ERROR] /home/marvin/git/fenixedu-spaces/src/main/java/org/fenixedu/spaces/domain/Space.java:132: warning: no description for @param
[ERROR] \* @param when
[ERROR] ^
[ERROR] /home/marvin/git/fenixedu-spaces/src/main/java/org/fenixedu/spaces/domain/Space.java:133: error: @param name not found
[ERROR] \* @param atWhatDate
[ERROR] ^
[ERROR] /home/marvin/git/fenixedu-spaces/src/main/java/org/fenixedu/spaces/domain/Space.java:133: warning: no description for @param
[ERROR] \* @param atWhatDate
[ERROR] ^
[ERROR] /home/marvin/git/fenixedu-spaces/src/main/java/org/fenixedu/spaces/domain/Space.java:134: warning: no description for @return
[ERROR] \* @return
[ERROR] ^
[ERROR] /home/marvin/git/fenixedu-spaces/src/main/java/org/fenixedu/spaces/domain/Space.java:137: warning: no @param for creationDate
[ERROR] protected Optional getInformation(final DateTime when, final DateTime creationDate) {
[ERROR] ^
[ERROR] /home/marvin/git/fenixedu-spaces/src/main/java/org/fenixedu/spaces/ui/SpaceOccupantsBean.java:123: warning: no @param for d1
[ERROR] public static boolean isAfter(DateTime d1, DateTime d2) {
[ERROR] ^
[ERROR] /home/marvin/git/fenixedu-spaces/src/main/java/org/fenixedu/spaces/ui/SpaceOccupantsBean.java:123: warning: no @param for d2
[ERROR] public static boolean isAfter(DateTime d1, DateTime d2) {
[ERROR] ^
[ERROR] /home/marvin/git/fenixedu-spaces/src/main/java/org/fenixedu/spaces/ui/SpaceOccupantsBean.java:123: warning: no @return
[ERROR] public static boolean isAfter(DateTime d1, DateTime d2) {
[ERROR] ^

**Comment by zhaoxi1988** [comment]
@jcarvalho   So what is your recommended actions? 

I meet the problem , too.

**Comment by zhaoxi1988** [comment]
@jcarvalho   So what is your recommended actions? 

I meet the problem , too.

**Comment by jcarvalho** [comment]
My recommendation is that Javadoc should **always** be validated.

If you project is small enough, the Javadoc Mojo should be attached to the `install` phase, otherwise, it should be explicitly invoked by your CI server.

**Comment by sergiofbsilva** [comment]
resolved in #7
