### ISSUE TITLE
Generate test domain code with in memory backend

### ISSUE THREAD

**Issue by diutsu** [FenixEdu/fenixedu-maven#5]
After fenix-framework/fenix-framework#219 add to the [fenix-framework-project/pom.xml](/FenixEdu/fenixedu-maven/fenix-framework-project/pom.xml) another execution to generate test domain with the in memory backend

**Comment by Luis-Cruz** [comment]
Resolved by https://github.com/FenixEdu/fenixedu-maven/pull/6
